import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent, type ReactNode } from "react";
import {
  PlaygroundApiClient,
  type IntelligenceTaskStatus,
  type JobStatus,
  type LocalInstanceStatus,
  type ProgressEvent,
  type SiteDetail,
  type SiteSummary,
  type SourceFile,
} from "./api-client";
import "./styles.css";
import { friendlyError } from "./error-messages";

const northSmilePrompt = `Create a modern responsive website for a dental clinic called NorthSmile Dental.

Pages: Home, Services, Dentists and Contact. Include a welcoming hero, clinic benefits, featured services, three dentist profiles, patient testimonials, opening hours and an appointment form. Use a clean medical aesthetic, strong typography, polished cards, clear navigation and responsive desktop/mobile layout.`;
const defaultPrompt = "Build a modern digital consulting company website with Home, Services, About, Testimonials and Contact. Include a working contact form.";
const presets = [
  { id: "saas", label: "SaaS", prompt: "Create a polished SaaS landing page for an AI productivity product with pricing, feature sections, testimonials and a sign-up CTA." },
  { id: "agency", label: "Agency", prompt: "Create a premium creative agency website with a bold hero, services, selected work, team, testimonials and a contact form." },
  { id: "portfolio", label: "Portfolio", prompt: "Create a modern personal portfolio with an introduction, selected projects, skills, about section and contact form." },
  { id: "restaurant", label: "Restaurant", prompt: "Create a responsive website for a neighborhood restaurant called Ember & Grain with menu, chef story, opening hours, location and reservation form." },
  { id: "dental", label: "Dental clinic", prompt: northSmilePrompt },
];
type ConnectionState = "loading" | "online" | "offline";
type WorkspaceMode = "PREVIEW" | "CODE";
type Viewport = "desktop" | "tablet" | "mobile";
const taskOrder = ["REQUIREMENTS_PLANNING", "DESIGN_PLANNING", "RUNTIME_PLANNING", "AUTH_PLANNING", "INTEGRATION_PLANNING", "CONTENT_GENERATION", "CODE_GENERATION", "BUILD_REPAIR", "TARGETED_EDIT"] as const;
const taskNames: Partial<Record<IntelligenceTaskStatus["taskKind"], string>> = {
  REQUIREMENTS_PLANNING: "Requirements", DESIGN_PLANNING: "Design", RUNTIME_PLANNING: "Runtime planning", AUTH_PLANNING: "Auth planning", INTEGRATION_PLANNING: "Integration planning", CONTENT_GENERATION: "Content", CODE_GENERATION: "Site coder", BUILD_REPAIR: "Build repair", TARGETED_EDIT: "Targeted editing",
};
const workflowLabels: Record<string, string> = { QUEUED: "Understanding request", PLANNING: "Understanding request", DESIGNING: "Understanding request", CREATING_ENVIRONMENT: "Preparing site", GENERATING: "Generating website", BUILDING: "Building", PREVIEW_READY: "Checking website", QA_RUNNING: "Checking website", SAVING: "Checking website", COMPLETED: "Ready", FAILED: "Needs attention" };
const workflowOrder = ["Understanding request", "Preparing site", "Generating website", "Building", "Checking website", "Ready"];
const formatTime = (value?: string) => value ? new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "--";
const readableError = (reason: unknown, fallback: string) => reason instanceof Error ? reason.message : fallback;
export function App() {
  const api = useMemo(() => new PlaygroundApiClient(), []);
  const jobController = useRef<AbortController | undefined>(undefined);
  const [sites, setSites] = useState<SiteSummary[]>([]);
  const [detail, setDetail] = useState<SiteDetail>();
  const [selectedVersion, setSelectedVersion] = useState<string>();
  const [prompt, setPrompt] = useState(defaultPrompt);
  const [editPrompt, setEditPrompt] = useState("");
  const [events, setEvents] = useState<ProgressEvent[]>([]);
  const [intelligence, setIntelligence] = useState<IntelligenceTaskStatus[]>([]);
  const [busy, setBusy] = useState(false);
  const [runStatus, setRunStatus] = useState<JobStatus["status"]>();
  const [activeJob, setActiveJob] = useState<JobStatus>();
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<{ id: string; url: string; versionId: string }>();
  const [instance, setInstance] = useState<LocalInstanceStatus>();
  const [viewport, setViewport] = useState<Viewport>("desktop");
  const [frameKey, setFrameKey] = useState(0);
  const [connection, setConnection] = useState<ConnectionState>("loading");
  const [mode, setMode] = useState<WorkspaceMode>("PREVIEW");
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [files, setFiles] = useState<SourceFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<string>();
  const [fileContents, setFileContents] = useState<Record<string, string>>({});
  const [sourceLoading, setSourceLoading] = useState(false);
  const [sourceError, setSourceError] = useState("");

  const reloadSites = async () => setSites(await api.sites());
  useEffect(() => { void Promise.all([reloadSites(), api.health()]).then(([, health]) => setConnection(health.status === "ok" ? "online" : "offline")).catch(() => setConnection("offline")); return () => jobController.current?.abort(); }, []);
  useEffect(() => {
    if (!preview) { setInstance(undefined); return; }
    let active = true; let timer: ReturnType<typeof setTimeout>;
    const refresh = () => void api.previewInstance(preview.id).then((value) => active && setInstance(value)).catch(() => active && setInstance(undefined)).finally(() => { if (active) timer = setTimeout(refresh, 2_000); });
    refresh(); return () => { active = false; clearTimeout(timer); };
  }, [api, preview?.id]);
  const openSite = async (id: string) => {
    try {
      const value = await api.site(id); const versionId = value.project.latestVersionId ?? value.versions.at(-1)?.versionId;
      setDetail(value); setSelectedVersion(versionId); setFiles([]); setSelectedFile(undefined); setFileContents({}); setError("");
      const active = value.activePreview;
      if (active && active.versionId === versionId) setPreview({ id: active.previewSessionId, url: active.previewUrl, versionId: active.versionId }); else setPreview(undefined);
    } catch (reason) { setError(readableError(reason, "Unable to open project")); }
  };
  const newRun = () => { setDetail(undefined); setSelectedVersion(undefined); setPreview(undefined); setMode("PREVIEW"); setError(""); };
  const stopPreview = async () => { if (!preview) return; try { await api.stopPreview(preview.id); setPreview(undefined); setInstance(undefined); } catch (reason) { setError(readableError(reason, "Unable to stop preview")); } };
  const startVersionPreview = async (siteId: string, versionId: string) => { if (preview) await api.stopPreview(preview.id); const value = await api.preview(siteId, versionId); setPreview({ id: value.previewSessionId, url: value.previewUrl, versionId }); };
  const selectVersion = async (versionId: string) => { setSelectedVersion(versionId); setFiles([]); setSelectedFile(undefined); if (detail && preview?.versionId !== versionId) try { await startVersionPreview(detail.project.projectId, versionId); } catch (reason) { setError(readableError(reason, "Unable to load this version's preview")); } };
  const followJob = (jobId: string) => new Promise<JobStatus>((resolve, reject) => {
    jobController.current?.abort(); const controller = new AbortController(); jobController.current = controller; setEvents([]); setIntelligence([]); setActiveJob(undefined); setRunStatus("QUEUED");
    let timer: ReturnType<typeof setTimeout>; let done = false; const stopEvents = api.events(jobId, (event) => setEvents((current) => [...current, event].slice(-300)), (task) => setIntelligence((current) => [...current.filter((item) => item.taskKind !== task.taskKind), task]));
    const cleanup = () => { done = true; clearTimeout(timer); stopEvents(); controller.signal.removeEventListener("abort", cancel); }; const cancel = () => { cleanup(); reject(new Error("Stopped following job")); }; controller.signal.addEventListener("abort", cancel, { once: true });
    const poll = () => void api.job(jobId, controller.signal).then((job) => { if (done) return; setActiveJob(job); setRunStatus(job.status); setIntelligence(job.intelligence ?? []); if (job.status === "SUCCEEDED" || job.status === "FAILED") { cleanup(); if (job.status === "FAILED") reject(Object.assign(new Error(job.error?.message ?? "Job failed"), { job })); else resolve(job); } }).catch((reason) => { cleanup(); reject(reason instanceof Error ? reason : new Error("Unable to read job status")); }).finally(() => { if (!done) timer = setTimeout(poll, 500); });
    poll();
  });
  const finishSuccess = async (job: JobStatus, siteId?: string) => { await reloadSites(); if (siteId ?? job.projectId) await openSite(siteId ?? job.projectId!); if (job.preview && job.versionId) setPreview({ id: job.preview.sessionId, url: job.preview.url, versionId: job.versionId }); };
  const generate = async () => { if (prompt.trim().length < 3) return; setBusy(true); setError(""); setMode("PREVIEW"); try { const { jobId } = await api.generate(prompt.trim()); await finishSuccess(await followJob(jobId)); } catch (reason) { const job = (reason as { job?: JobStatus }).job; if (job) setActiveJob(job); setError(friendlyError(job, readableError(reason, "We couldn't finish this website."))); } finally { setBusy(false); } };
  const edit = async () => { if (!detail || editPrompt.trim().length < 3) return; const siteId = detail.project.projectId; setBusy(true); setError(""); try { const { jobId } = await api.edit(siteId, editPrompt.trim(), selectedVersion); await finishSuccess(await followJob(jobId), siteId); setEditPrompt(""); } catch (reason) { const job = (reason as { job?: JobStatus }).job; if (job) setActiveJob(job); setError(friendlyError(job, "We couldn't apply that change.")); } finally { setBusy(false); } };
  const deleteSite = async (site: SiteSummary) => { if (!confirm(`Delete ${site.name} and all of its local versions? This cannot be undone.`)) return; try { await api.deleteSite(site.projectId); if (detail?.project.projectId === site.projectId) newRun(); await reloadSites(); } catch (reason) { setError(readableError(reason, "Unable to delete project")); } };
  const loadSourceFiles = async () => { if (!detail || !selectedVersion) return; setSourceLoading(true); setSourceError(""); try { const value = await api.sourceFiles(detail.project.projectId, selectedVersion); setFiles(value.files); const firstText = value.files.find((file) => !file.encoding); setSelectedFile((current) => current && value.files.some((file) => file.path === current) ? current : firstText?.path); } catch (reason) { setSourceError(readableError(reason, "Unable to load generated source")); } finally { setSourceLoading(false); } };
  useEffect(() => { if (detail && selectedVersion) void loadSourceFiles(); }, [detail?.project.projectId, selectedVersion]);
  useEffect(() => { if (!detail || !selectedVersion || !selectedFile || files.find((file) => file.path === selectedFile)?.encoding) return; const key = `${selectedVersion}:${selectedFile}`; if (fileContents[key] !== undefined) return; setSourceLoading(true); setSourceError(""); void api.sourceFile(detail.project.projectId, selectedVersion, selectedFile).then((value) => setFileContents((current) => ({ ...current, [key]: value.content }))).catch((reason) => setSourceError(readableError(reason, "Unable to load source file"))).finally(() => setSourceLoading(false)); }, [detail?.project.projectId, selectedVersion, selectedFile, files]);
  const currentVersion = detail?.versions.find((version) => version.versionId === selectedVersion); const currentSource = selectedVersion && selectedFile ? fileContents[`${selectedVersion}:${selectedFile}`] : undefined; const currentStage = activeJob?.currentStage ?? events.at(-1)?.stage ?? "QUEUED";
  return <div className="sites-module"><header className="sites-module-header"><button className="sites-module-title" onClick={newRun} aria-label="Open Sites"><span className="sites-module-mark">S</span><span><strong>Sites</strong><small>Website builder</small></span></button><div className="sites-module-actions"><span className={`connection-state ${connection}`}><i />{connection === "online" ? "Ready" : connection === "loading" ? "Connecting" : "Offline"}</span><button className="icon-button" aria-label="Refresh projects" onClick={() => void reloadSites()}>↻</button></div></header><main className="sites-content">{!detail && !busy && <StartScreen sites={sites} busy={busy} onNew={newRun} onOpen={openSite} onDelete={deleteSite} prompt={prompt} setPrompt={setPrompt} onGenerate={generate} />}{!detail && busy && <GenerationView events={events} currentStage={currentStage} runStatus={runStatus} viewport={viewport} setViewport={setViewport} />}{detail && <ProjectWorkspace detail={detail} selectedVersion={selectedVersion} currentVersion={currentVersion} onBack={newRun} onSelectVersion={selectVersion} mode={mode} setMode={setMode} viewport={viewport} setViewport={setViewport} preview={preview} frameKey={frameKey} refreshPreview={() => setFrameKey((key) => key + 1)} onStartPreview={() => detail && selectedVersion ? void startVersionPreview(detail.project.projectId, selectedVersion) : undefined} onStopPreview={() => void stopPreview()} instance={instance} files={files} selectedFile={selectedFile} setSelectedFile={setSelectedFile} currentSource={currentSource} sourceLoading={sourceLoading} sourceError={sourceError} editPrompt={editPrompt} setEditPrompt={setEditPrompt} onEdit={edit} busy={busy} setDetailsOpen={setDetailsOpen} />}{error && <ErrorNotice message={error} job={activeJob} onRetry={detail ? edit : generate} onDetails={() => setDetailsOpen(true)} canRetry={!busy && (detail ? editPrompt.trim().length >= 3 : prompt.trim().length >= 3)} />}</main>{detailsOpen && <TechnicalDetails job={activeJob} intelligence={intelligence} events={events} version={currentVersion} previewReused={Boolean(preview)} onClose={() => setDetailsOpen(false)} />}</div>;
}

function SitesProjects({ sites, busy, onNew, onOpen, onDelete }: { sites: SiteSummary[]; busy: boolean; onNew: () => void; onOpen: (id: string) => void; onDelete: (site: SiteSummary) => void }) { return <section className="sites-projects" aria-label="Recent Sites"><div className="sites-projects-heading"><div><span className="overline">SITES</span><h2>Recent sites</h2></div><button className="new-project" onClick={onNew}>＋ New website</button></div>{sites.length ? <div className="sites-project-grid">{sites.map((site) => <article className="site-project-card" key={site.projectId}><button className="site-project-open" onClick={() => onOpen(site.projectId)}><span className="project-avatar">{site.name.slice(0, 1).toUpperCase()}</span><span><strong>{site.name}</strong><small>{site.latestVersion ? `Version ${site.latestVersion}` : "In progress"}</small></span></button><button className="delete-project" aria-label={`Delete ${site.name}`} disabled={busy} onClick={() => onDelete(site)}>×</button></article>)}</div> : <div className="sites-projects-empty">Your generated sites will appear here.</div>}</section>; }
function StartScreen({ sites, busy, onNew, onOpen, onDelete, prompt, setPrompt, onGenerate }: { sites: SiteSummary[]; busy: boolean; onNew: () => void; onOpen: (id: string) => void; onDelete: (site: SiteSummary) => void; prompt: string; setPrompt: (value: string) => void; onGenerate: () => void }) { const submit = (event: FormEvent) => { event.preventDefault(); onGenerate(); }; return <section className="start-screen"><div className="start-copy"><span className="eyebrow">SITES</span><h1>What do you want to build?</h1><p>Describe your website and Sites will build it for you.</p></div><PromptComposer value={prompt} setValue={setPrompt} onSubmit={submit} buttonLabel="Generate" placeholder="Build a modern SaaS website for an AI meeting assistant..." /><div className="example-section"><div className="section-label"><span>Try an example</span><small>Or write your own prompt</small></div><div className="preset-grid">{presets.map((preset) => <button className="preset-chip" key={preset.id} onClick={() => setPrompt(preset.prompt)}><span>{preset.label}</span><i>↗</i></button>)}</div></div><div className="start-note"><span>✦</span><span>Every site includes a responsive layout, live preview and readable source code.</span></div><SitesProjects sites={sites} busy={busy} onNew={onNew} onOpen={onOpen} onDelete={onDelete} /></section>; }
function PromptComposer({ value, setValue, onSubmit, buttonLabel, placeholder }: { value: string; setValue: (value: string) => void; onSubmit: (event: FormEvent) => void; buttonLabel: string; placeholder: string }) { const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") { event.preventDefault(); onSubmit(event); } }; return <form className="prompt-composer" onSubmit={onSubmit}><textarea aria-label={placeholder} value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={onKeyDown} placeholder={placeholder} rows={5} /><div className="composer-footer"><span className="composer-hint"><kbd>⌘</kbd><kbd>↵</kbd> to generate</span><button className="primary-button" type="submit">{buttonLabel}<span>→</span></button></div></form>; }
function GenerationView({ events, currentStage, runStatus, viewport, setViewport }: { events: ProgressEvent[]; currentStage: string; runStatus?: JobStatus["status"]; viewport: Viewport; setViewport: (value: Viewport) => void }) { const currentLabel = workflowLabels[currentStage] ?? "Generating website"; const reached = new Set(events.map((event) => workflowLabels[event.stage]).filter(Boolean)); if (runStatus === "SUCCEEDED") reached.add("Ready"); const activeIndex = Math.max(0, workflowOrder.indexOf(currentLabel)); return <section className="generating-screen"><div className="generation-card"><div className="generation-title"><span className="loader" /><div><span className="eyebrow">WORKING ON IT</span><h1>Building your website</h1><p>We’re turning your idea into a real, responsive site.</p></div></div><div className="friendly-steps">{workflowOrder.slice(0, Math.max(activeIndex + 1, reached.size || 1)).map((label, index) => <div className={`friendly-step ${reached.has(label) || index < activeIndex ? "done" : index === activeIndex ? "current" : ""}`} key={label}><span>{reached.has(label) || index < activeIndex ? "✓" : index === activeIndex ? "•" : "○"}</span><strong>{label}</strong></div>)}</div><div className="generation-events">{events.slice(-3).map((event, index) => <p key={`${event.timestamp}-${index}`}>{event.message}</p>)}</div></div><div className="waiting-preview"><div className="preview-topline"><span>Live preview</span><span className="preview-badge">Preparing</span></div><div className="preview-placeholder"><div className="placeholder-window"><span /><span /><span /></div><strong>Your website will appear here</strong><small>Preview becomes available when the build is ready.</small></div><ViewportSwitcher viewport={viewport} setViewport={setViewport} /></div></section>; }
function ProjectWorkspace({ detail, selectedVersion, currentVersion, onBack, onSelectVersion, mode, setMode, viewport, setViewport, preview, frameKey, refreshPreview, onStartPreview, onStopPreview, instance, files, selectedFile, setSelectedFile, currentSource, sourceLoading, sourceError, editPrompt, setEditPrompt, onEdit, busy, setDetailsOpen }: { detail: SiteDetail; selectedVersion?: string; currentVersion?: SiteDetail["versions"][number]; onBack: () => void; onSelectVersion: (id: string) => void; mode: WorkspaceMode; setMode: (mode: WorkspaceMode) => void; viewport: Viewport; setViewport: (viewport: Viewport) => void; preview?: { id: string; url: string; versionId: string }; frameKey: number; refreshPreview: () => void; onStartPreview: () => void; onStopPreview: () => void; instance?: LocalInstanceStatus; files: SourceFile[]; selectedFile?: string; setSelectedFile: (path?: string) => void; currentSource?: string; sourceLoading: boolean; sourceError: string; editPrompt: string; setEditPrompt: (value: string) => void; onEdit: () => void; busy: boolean; setDetailsOpen: (open: boolean) => void }) { const status = busy ? "Building" : currentVersion?.browserQAStatus === "FAILED" || currentVersion?.buildStatus === "FAILED" ? "Needs attention" : currentVersion ? "Saved" : "Ready"; return <section className="workspace-screen"><header className="workspace-header"><div className="workspace-title"><button className="back-button" onClick={onBack}>← <span>Projects</span></button><div><h1>{detail.project.name}</h1><span>{detail.project.slug}</span></div></div><div className="workspace-actions"><StatusPill status={status} /><VersionSelector versions={detail.versions} selectedVersion={selectedVersion} onSelect={onSelectVersion} /><button className="details-button" onClick={() => setDetailsOpen(true)}>View details</button></div></header><div className="workspace-body"><ConversationPanel detail={detail} editPrompt={editPrompt} setEditPrompt={setEditPrompt} onEdit={onEdit} busy={busy} /><section className="canvas"><div className="canvas-header"><div className="mode-switcher" role="tablist" aria-label="Workspace view"><button className={mode === "PREVIEW" ? "active" : ""} onClick={() => setMode("PREVIEW")} role="tab" aria-selected={mode === "PREVIEW"}>Preview</button><button className={mode === "CODE" ? "active" : ""} onClick={() => setMode("CODE")} role="tab" aria-selected={mode === "CODE"}>Code</button></div>{mode === "PREVIEW" ? <ViewportSwitcher viewport={viewport} setViewport={setViewport} /> : <span className="readonly-label">Read-only source</span>}</div>{mode === "PREVIEW" ? <PreviewPanel preview={preview} frameKey={frameKey} viewport={viewport} onRefresh={refreshPreview} onStart={onStartPreview} onStop={onStopPreview} instance={instance} /> : <CodePanel files={files} selectedFile={selectedFile} setSelectedFile={setSelectedFile} content={currentSource} loading={sourceLoading} error={sourceError} />}</section></div></section>; }
function ConversationPanel({ detail, editPrompt, setEditPrompt, onEdit, busy }: { detail: SiteDetail; editPrompt: string; setEditPrompt: (value: string) => void; onEdit: () => void; busy: boolean }) { const submit = (event: FormEvent) => { event.preventDefault(); onEdit(); }; return <aside className="conversation"><div className="conversation-heading"><span className="eyebrow">CONVERSATION</span><h2>Keep shaping it</h2></div><div className="messages"><div className="message user-message"><span className="message-avatar">You</span><div><small>You asked</small><p>{detail.project.name} website</p></div></div><div className="message sites-message"><span className="message-avatar sites-avatar">S</span><div><small>Sites</small><p>Your website is ready to explore. Ask for a change whenever you like.</p></div></div></div><form className="edit-composer" onSubmit={submit}><textarea aria-label="Ask Sites for a change" value={editPrompt} onChange={(event) => setEditPrompt(event.target.value)} placeholder="Ask Sites for a change..." rows={4} /><div><span>Describe a visual or content change</span><button className="send-button" disabled={busy || editPrompt.trim().length < 3} type="submit">{busy ? "Updating…" : "Send change"}<b>↑</b></button></div></form></aside>; }
function PreviewPanel({ preview, frameKey, viewport, onRefresh, onStart, onStop, instance }: { preview?: { id: string; url: string; versionId: string }; frameKey: number; viewport: Viewport; onRefresh: () => void; onStart: () => void; onStop: () => void; instance?: LocalInstanceStatus }) { return <div className="preview-area"><div className="preview-toolbar"><div><span className={`live-indicator ${preview ? "on" : ""}`} />{preview ? "Live preview" : "Preview not started"}</div><div className="preview-toolbar-actions">{preview ? <><button onClick={onRefresh} aria-label="Refresh preview">↻</button><button onClick={onStop}>Stop</button><a href={preview.url} target="_blank" rel="noreferrer">Open ↗</a></> : <button className="toolbar-primary" onClick={onStart}>Open preview</button>}</div></div><div className="iframe-stage">{preview ? <iframe key={frameKey} title="Generated website preview" src={preview.url} className={`viewport-${viewport}`} /> : <div className="empty-preview"><div className="empty-preview-icon">✦</div><h2>Preview your website</h2><p>Start the preview to see this version come to life.</p><button className="primary-button" onClick={onStart}>Open preview <span>→</span></button></div>}</div>{instance && <details className="preview-instance"><summary>Preview is running <span>View local details</span></summary><div><span>Environment <b>{instance.environmentId}</b></span><span>Processes <b>{instance.processCount}</b></span></div></details>}</div>; }
function ViewportSwitcher({ viewport, setViewport }: { viewport: Viewport; setViewport: (viewport: Viewport) => void }) { return <div className="viewport-switcher" aria-label="Preview size"><button className={viewport === "desktop" ? "active" : ""} onClick={() => setViewport("desktop")}>Desktop</button><button className={viewport === "tablet" ? "active" : ""} onClick={() => setViewport("tablet")}>Tablet</button><button className={viewport === "mobile" ? "active" : ""} onClick={() => setViewport("mobile")}>Mobile</button></div>; }
type TreeEntry = { path: string; label: string; folder: boolean; children?: TreeEntry[] };
function CodePanel({ files, selectedFile, setSelectedFile, content, loading, error }: { files: SourceFile[]; selectedFile?: string; setSelectedFile: (path?: string) => void; content?: string; loading: boolean; error: string }) { return <div className="code-area"><aside className="file-tree"><div className="file-tree-heading">FILES <span>{files.filter((file) => !file.encoding).length}</span></div>{loading && !files.length ? <div className="tree-message">Loading files…</div> : error && !files.length ? <div className="tree-message error-text">{error}</div> : buildFileTree(files.filter((file) => !file.encoding)).map((entry) => <FileTreeEntry entry={entry} key={entry.path} selectedFile={selectedFile} setSelectedFile={setSelectedFile} />)}</aside><section className="code-viewer"><div className="code-header"><span>{selectedFile ?? "Select a file"}</span>{selectedFile && <button onClick={() => content && void navigator.clipboard?.writeText(content)}>Copy</button>}</div>{error && files.length ? <div className="code-empty error-text">{error}</div> : !selectedFile ? <div className="code-empty">Select a source file to inspect it.</div> : loading && content === undefined ? <div className="code-empty">Loading source…</div> : <pre className="source-code" aria-label={`${selectedFile} source code`}><code>{(content ?? "").split("\n").map((line, index) => <span className="code-line" key={index}><i>{index + 1}</i><b>{highlightLine(line, selectedFile)}</b></span>)}</code></pre>}</section></div>; }
function buildFileTree(files: SourceFile[]): TreeEntry[] { const root: TreeEntry[] = []; for (const file of files.slice().sort((a, b) => a.path.localeCompare(b.path))) { let current = root; const parts = file.path.split("/"); parts.forEach((part, index) => { const path = parts.slice(0, index + 1).join("/"); let entry = current.find((item) => item.path === path); if (!entry) { entry = { path, label: part, folder: index < parts.length - 1, ...(index < parts.length - 1 ? { children: [] } : {}) }; current.push(entry); } current = entry.children ?? []; }); } return root; }
function FileTreeEntry({ entry, selectedFile, setSelectedFile }: { entry: TreeEntry; selectedFile?: string; setSelectedFile: (path?: string) => void }) { const [open, setOpen] = useState(true); if (entry.folder) return <div className="tree-folder"><button onClick={() => setOpen((value) => !value)}><span>{open ? "⌄" : "›"}</span> {entry.label}</button>{open && <div>{entry.children?.map((child) => <FileTreeEntry entry={child} key={child.path} selectedFile={selectedFile} setSelectedFile={setSelectedFile} />)}</div>}</div>; return <button className={`tree-file ${selectedFile === entry.path ? "selected" : ""}`} onClick={() => setSelectedFile(entry.path)}><span>•</span>{entry.label}</button>; }
function highlightLine(line: string, path = "") { const parts = line.split(/(\/\/.*|\/\*.*?\*\/|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\b(?:const|let|var|function|return|export|default|import|from|interface|type|class|extends|if|else|true|false|null|undefined|async|await)\b|\b\d+(?:\.\d+)?\b)/g); return parts.map((part, index) => { const kind = /^\/\//.test(part) || /^\/\*/.test(part) ? "comment" : /^(?:const|let|var|function|return|export|default|import|from|interface|type|class|extends|if|else|true|false|null|undefined|async|await)$/.test(part) ? "keyword" : /^\d/.test(part) ? "number" : /^(?:["'`])/.test(part) ? "string" : path.endsWith(".css") && /--?[a-z-]+/.test(part) ? "property" : ""; return <span className={kind} key={`${index}-${part}`}>{part}</span>; }); }
function VersionSelector({ versions, selectedVersion, onSelect }: { versions: SiteDetail["versions"]; selectedVersion?: string; onSelect: (id: string) => void }) { return <label className="version-selector"><span>Version</span><select value={selectedVersion ?? ""} onChange={(event) => onSelect(event.target.value)} aria-label="Select version">{versions.slice().reverse().map((version) => <option value={version.versionId} key={version.versionId}>V{version.versionNumber}{version.versionId === selectedVersion ? " · Current" : ""}</option>)}</select></label>; }
function StatusPill({ status }: { status: string }) { return <span className={`status-pill ${status.toLowerCase().replace(" ", "-")}`}><i />{status}</span>; }
function ErrorNotice({ message, job, onRetry, onDetails, canRetry }: { message: string; job?: JobStatus; onRetry: () => void; onDetails: () => void; canRetry: boolean }) {
  const failure = job?.error;
  return <section className="error-notice" role="alert"><div className="error-icon">!</div><div>
    <h2>{message.includes("couldn't") ? message : "We couldn't finish this website"}</h2>
    <p>{message}</p>
    {failure && <small>
      {failure.status !== undefined && <>HTTP {failure.status} · </>}
      {failure.providerCode ?? failure.code}
      {failure.providerParam && <> · {failure.providerParam}</>}
      {failure.requestId && <> · Request {failure.requestId}</>}
    </small>}
    <div className="error-actions"><button onClick={onDetails}>View details</button><button className="primary-button small" disabled={!canRetry} onClick={onRetry}>Try again</button></div>
    {failure?.retryable && <small>This issue may resolve if you try again shortly.</small>}
  </div></section>;
}
function TechnicalDetails({ job, intelligence, events, version, previewReused, onClose }: { job?: JobStatus; intelligence: IntelligenceTaskStatus[]; events: ProgressEvent[]; version?: SiteDetail["versions"][number]; previewReused: boolean; onClose: () => void }) { const ordered = intelligence.slice().sort((a, b) => taskOrder.indexOf(a.taskKind as never) - taskOrder.indexOf(b.taskKind as never)); const input = intelligence.reduce((sum, item) => sum + (item.inputTokens ?? 0), 0); const output = intelligence.reduce((sum, item) => sum + (item.outputTokens ?? 0), 0); return <div className="details-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="details-drawer" role="dialog" aria-modal="true" aria-label="Technical details"><header><div><span className="eyebrow">DEVELOPER VIEW</span><h2>Run details</h2></div><button onClick={onClose} aria-label="Close details">×</button></header><div className="details-content"><DetailGroup title="Run"><DetailRow label="Job ID" value={job?.id ?? "—"} mono /><DetailRow label="Status" value={job?.status ?? "Ready"} /><DetailRow label="Last stage" value={job?.currentStage ?? events.at(-1)?.stage ?? "—"} /></DetailGroup><DetailGroup title="Provider"><DetailRow label="Provider" value={intelligence[0]?.provider ?? "—"} /><DetailRow label="Model" value={intelligence[0]?.model ?? "—"} /></DetailGroup><DetailGroup title="Usage"><DetailRow label="Request profile" value={intelligence.some((item) => item.attempted) ? "Active" : "Deterministic"} /><DetailRow label="Planner calls" value={String(intelligence.filter((item) => /PLANNING|CONTENT/.test(item.taskKind) && item.attempted).length)} /><DetailRow label="Input tokens" value={String(input)} /><DetailRow label="Output tokens" value={String(output)} /><DetailRow label="Total tokens" value={String(input + output)} /></DetailGroup><DetailGroup title="Checks"><DetailRow label="Build" value={version?.buildStatus === "SUCCEEDED" ? "PASS" : version?.buildStatus ?? "—"} /><DetailRow label="Browser QA" value={version?.browserQAStatus ?? "—"} /><DetailRow label="Build repair used" value={intelligence.some((item) => item.taskKind === "BUILD_REPAIR" && item.attempted) ? "YES" : "NO"} /><DetailRow label="Preview reused" value={previewReused ? "YES" : "NO"} /></DetailGroup>{job?.error?.diagnostics && <DetailGroup title="Build diagnostics"><pre className="source-code"><code>{job.error.diagnostics}</code></pre></DetailGroup>}<DetailGroup title="Task trace">{ordered.length ? ordered.map((item) => <div className="task-row" key={item.taskKind}><span>{taskNames[item.taskKind] ?? item.taskKind}</span><b data-status={item.status}>{item.status}</b></div>) : <p className="muted-copy">No run telemetry available.</p>}</DetailGroup></div></aside></div>; }
function DetailGroup({ title, children }: { title: string; children: ReactNode }) { return <section className="detail-group"><h3>{title}</h3>{children}</section>; }
function DetailRow({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="detail-row"><span>{label}</span><b className={mono ? "mono" : ""}>{value}</b></div>; }
